### ISSUE TITLE
No hover state when cursor is over the 'Save Changes' or 'Submit Review' buttons on review form

### ISSUE THREAD

**Issue by gsloan** [fluenttechnology/northstar#42] opened 2018-09-19 14:25 UTC
Cursor does not change to indicate that these buttons are clickable:
![image](https://user-images.githubusercontent.com/5477755/45759551-0d205c00-bc20-11e8-9377-5abd5a5fab98.png)

The same also applies to the 'Send Review' button on the confirmation modal
![image](https://user-images.githubusercontent.com/5477755/45759629-35a85600-bc20-11e8-8d14-38aea2f7ba4f.png)

**Comment by goofballLogic** [comment] 2018-09-19 15:54
hey that's CSS man - don't drag me into that mess

**Comment by goofballLogic** [comment] 2018-09-19 16:02
Buttons should actually have the arrow pointer - that's good web UX. The real problem would be if we have any buttons which show the hand cursor wouldn't it? See https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b for a treatment. Thoughts @Chris-Shields ?

**Comment by gsloan** [comment] 2018-09-19 16:10
![image](https://user-images.githubusercontent.com/5477755/45765998-6b543b80-bc2e-11e8-9e25-129af547927c.png)

**Comment by Chris-Shields** [comment] 2018-09-20 08:13
@goofballLogic @gsloan I have views on this, though we've talked about it before. I believe it was even a github issue to remove them on the first prototype:

- W3C,Apple and Microsoft, all say that cursors are used to support weak affordance and are only used with links
- @goofballLogic friend Adam Silver likes to write about this a lot, I'm fairly certain he accounts for like 90% of the web discussion
- Skeuomorphic shizzle

I have to look at comments like Gordon's original issue ponder if the pointer is now the expectation on the web, as it's been overused for many many years now. Even myself, I feel there is less affordance on a button when it's not shown to have a cursor state, again due to the expectations from years of web use. Yes, this has came about from bad design trends and patterns over the years, but perhaps it's what many people expect to happen.

Adam Silver said "_If we’re going against standards, then it seems more appropriate to ask: does the pointer cursor on (well-designed) buttons help the user achieve their goal?_" Which for me hits the nail on the head. If adding cursor pointers to a button helps achieve their goal, then it's probably worth it. If it doesn't then don't.

Looking at our design 

![image](https://user-images.githubusercontent.com/31107754/45803531-c24f2480-bcb1-11e8-914c-062effcda489.png)

We see a link and a button sitting next to each other. The link, on the left, performs a navigation action and closes the modal. The button on the right, performs a data submission. Ok, so far, working as intended. However, one has a cursor pointer and the other does not. This sort of inconsistency could be confusing to the user. One option is to say that the cancel is to button-ish and should be a simple hyperlink, which design wise I could accept as a perfectly legitimate solution as the level of differentiation is much higher. However, then we have the dashboard

![image](https://user-images.githubusercontent.com/31107754/45803695-2540bb80-bcb2-11e8-9373-618bce9501d2.png)

This is also a link, but it also needs to be a focal point for the page, a call to action. They don't look as prominent whenever they are just text

![image](https://user-images.githubusercontent.com/31107754/45803816-6d5fde00-bcb2-11e8-830d-7b5c964610ea.png)

So we have an issue of trying to make them stand out as the most important actions on the page, whilst still making them respond like the hyperlinks that they are. Looking at the link icons in the above picture, they actually aren't that bad.. 

So thoughts here are welcome, as this will be a never-ending battle with many casualties and pingpong balls exchanged. We can either

A: Add hover states to our buttons and break standards, possibly making @goofballLogic lose faith in humanity. Cats and dogs living as one, mass hysteria.
B: Change the hyperlinks on the prototype to traditional hyperlink styling, making the dashboard call to action links a little less prominent

**Comment by goofballLogic** [comment] 2018-09-20 08:45
> We see a link and a button sitting next to each other. The link, on the left, performs a navigation action and closes the modal. 

It's worth noting that "closing the modal" is actually part of the concept of navigation in a RESTful application. Think of it as navigation from "state A has a modal dialog" to "state B has no modal dialog"

**Comment by goofballLogic** [comment] 2018-09-20 08:49
> This sort of inconsistency could be confusing to the user.

how so?

**Comment by goofballLogic** [comment] 2018-09-20 08:49
> friend
nope

**Comment by goofballLogic** [comment] 2018-09-20 12:16
tbh as we are in a modal dialog, I could be persuaded that they should both be buttons. i.e. cancel isn't "pure" navigation - it's closing a modal dialog. But equally, if you want to keep it as a link, I agree the styling should change

**Comment by Chris-Shields** [comment] 2018-09-20 12:59
I quite like the underline style for cancel, it feels less prominent and as such the desired action is lifted.  I'll swap around the styles and see how I feel about it on screen.

**Closed** 2018-09-25 08:19 UTC
Labels: CSS, bug, question, religious, theoretical
